# Site Settings
title: Terry Bryant
email: dageda1991@163.com
description: 一支穿云箭，千军万马来相见
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://terrybryant.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Terry
user_description: Are you OK?
disqus_username: none

# Social Media
# Remove the item if you don't need it
github_username: TerryBryant
weibo_username: 2346631012
# facebook_username: facebook_username
# twitter_username: twitter_username
# instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
